Fix preprocessing of several ##
```
 #define MAX_FOO (2 * 1)
 #define MAX_FOO_AA (3 * 1)

 #define M(UpperCaseName, b)                \
  do {                                     \
    int MaxValue = MAX_##UpperCaseName;    \
    if (b) {                               \
      MaxValue = MAX_##UpperCaseName##_AA; \
    }                                      \
  } while (0)

static void f(bool b) { M(FOO, b); }
```

was a preprocessor error
`a.cpp:4:0: error: failed to expand 'M', Invalid ## usage when expanding 'M'. [preprocessorErrorDirective]`
because `MAX_##UpperCaseName##_AA` was expanded to (2 * 1)##_AA, while gcc or clang happily expand it to `(3 * 1)`.